spring:
  application:
    name: book-lovers-kingdom
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
        
    
  datasource:
    url: jdbc:mysql://localhost:3306/mybookloverkingdomdb
    username: root
    password: Alpha123
